Repository discordjs/discord.js-modules, pull requests merged in 2020-03, with the labels that each got.

#6 chore: cleanup PR template, support and contributing files
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SUPPORT.md
Labels: documentation

#7 docs: manual prettier over markdown files
  .github/CODE_OF_CONDUCT.md
  .github/COMMIT_CONVENTION.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#9 chore: json schema for all necessary files
  lerna.json
  package.json
  packages/collection/package.json
  packages/core/package.json
  packages/discord.js/package.json
  packages/rest/package.json
  packages/types/package.json
  packages/voice/package.json
  packages/ws/package.json
Labels: collection, core, documentation, rest, types, voice, ws

#10 chore: tests
  package-lock.json
  package.json
Labels: collection, core, dependencies, documentation, rest, types, voice, ws

#12 chore: rename tests
  .github/workflows/lint-cron.yml
  .github/workflows/lint.yml
  .github/workflows/test-cron.yml
  .github/workflows/test.yml
  README.md
Labels: ci, documentation

#13 test: coverage
  .github/CONTRIBUTING.md
  .github/workflows/test-cron.yml
  .github/workflows/test.yml
  .gitignore
  lerna.json
  package.json
  packages/core/__tests__/index.test.ts
  packages/core/src/index.ts
Labels: ci, tests

#14 test: upload coverage
  .github/workflows/test.yml
  README.md
  package.json
Labels: ci, tests

#19 chore(pkg): install tslib on all packages
  packages/collection/package.json
  packages/core/package.json
  packages/discord.js/package.json
  packages/rest/package.json
  packages/types/package.json
  packages/voice/package.json
  packages/ws/package.json
Labels: collection, core, dependencies, rest, types, voice, ws

#18 chore(tsconfig): hoist generic compiler options
  packages/collection/tsconfig.json
  packages/core/tsconfig.json
  packages/discord.js/tsconfig.json
  packages/rest/tsconfig.json
  packages/types/tsconfig.json
  packages/voice/tsconfig.json
  packages/ws/tsconfig.json
  tsconfig.json
Labels: collection, core, refactor, rest, types, voice, ws

#17 docs: init typedoc
  .gitignore
  package-lock.json
  package.json
Labels: collection, core, documentation, rest, types, voice, ws

#20 docs: correct link to commit convention guide
  .github/CONTRIBUTING.md
Labels: documentation

#21 feat(collection): collection package
  packages/collection/__tests__/.gitkeep
  packages/collection/__tests__/collection.test.ts
  packages/collection/src/Collection.ts
  packages/collection/src/index.ts
Labels: collection
