Repository discordjs/discord.js-modules, pull requests merged in 2021-08, with the labels that each got.

#49 refactor(Rest): `xID` to `xId`
  packages/rest/src/lib/CDN.ts
  packages/rest/src/lib/RequestManager.ts
  packages/rest/src/lib/handlers/IHandler.ts
  packages/rest/src/lib/handlers/SequentialHandler.ts
Labels: semver:major, refactor

#50 chore: update repo/branch name
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/rest/CHANGELOG.md
  packages/rest/package.json
  packages/ws/CHANGELOG.md
  packages/ws/package.json
Labels: documentation

#47 chore: update Discord.js server invite
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/SUPPORT.md
Labels: documentation

#55 fix(Rest): use reference type for DOM
  package.json
  packages/rest/src/index.ts
  packages/rest/src/lib/RequestManager.ts
  packages/rest/tsconfig.json
Labels: semver:patch, types

#56 refactor(CDN): generalize method names
  packages/rest/__tests__/CDN.test.ts
  packages/rest/src/lib/CDN.ts
Labels: semver:major, rest

#54 chore: update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: documentation
